module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'chore',
        'docs',
        'test',
        'ci',
        'refactor',
        'perf',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'repo',
        'mobile',
        'deps',
        'lint',
        'quality',
        'github',
        'ci',
        'eas',
        'android',
        'ios',
        'db',
        'domain',
        'ui',
        'i18n',
        'capture',
        'notify',
        'followup',
        'home',
        'exercises',
        'stats',
        'settings',
        'export',
        'onboarding',
        'legal',
        'security',
        'a11y',
        'release',
        'api',
        'chat',
        'contracts',
        'crypto',
        'sync',
        'store',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
